////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2009 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version: L.57
//  \   \         Application: netgen
//  /   /         Filename: mult8_8.v
// /___/   /\     Timestamp: Mon Sep 09 22:54:51 2013
// \   \  /  \ 
//  \___\/\___\
//             
// Command	: -intstyle ise -w -sim -ofmt verilog D:\ModemPrograms\Chapter_6\E6_8_FpgaMskDemod\FpgaMskDemod\ipcore_dir\_cg\mult8_8.ngc D:\ModemPrograms\Chapter_6\E6_8_FpgaMskDemod\FpgaMskDemod\ipcore_dir\_cg\mult8_8.v 
// Device	: 6slx9csg225-2
// Input file	: D:/ModemPrograms/Chapter_6/E6_8_FpgaMskDemod/FpgaMskDemod/ipcore_dir/_cg/mult8_8.ngc
// Output file	: D:/ModemPrograms/Chapter_6/E6_8_FpgaMskDemod/FpgaMskDemod/ipcore_dir/_cg/mult8_8.v
// # of Modules	: 1
// Design Name	: mult8_8
// Xilinx        : D:\ProgramFiles\Xilinx\ISE\ISE
//             
// Purpose:    
//     This verilog netlist is a verification model and uses simulation 
//     primitives which may not represent the true implementation of the 
//     device, however the netlist is functionally correct and should not 
//     be modified. This file cannot be synthesized and should only be used 
//     with supported simulation tools.
//             
// Reference:  
//     Command Line Tools User Guide, Chapter 23 and Synthesis and Simulation Design Guide, Chapter 6
//             
////////////////////////////////////////////////////////////////////////////////

`timescale 1 ns/1 ps

module mult8_8 (
  clk, a, b, p
)/* synthesis syn_black_box syn_noprune=1 */;
  input clk;
  input [7 : 0] a;
  input [7 : 0] b;
  output [15 : 0] p;
  
  // synthesis translate_off
  
  wire \BU2/N1 ;
  wire NLW_VCC_P_UNCONNECTED;
  wire NLW_GND_G_UNCONNECTED;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_CARRYOUTF_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_CARRYOUT_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<17>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<16>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<15>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<14>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<13>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<12>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<11>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<10>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<9>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<8>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<7>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<6>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<5>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<4>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<3>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<2>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<1>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<0>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<47>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<46>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<45>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<44>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<43>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<42>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<41>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<40>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<39>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<38>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<37>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<36>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<35>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<34>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<33>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<32>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<31>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<30>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<29>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<28>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<27>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<26>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<25>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<24>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<23>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<22>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<21>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<20>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<19>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<18>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<17>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<16>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<15>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<14>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<13>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<12>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<11>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<10>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<9>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<8>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<7>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<6>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<5>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<4>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<3>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<2>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<1>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<0>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<47>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<46>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<45>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<44>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<43>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<42>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<41>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<40>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<39>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<38>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<37>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<36>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<35>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<34>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<33>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<32>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<31>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<30>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<29>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<28>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<27>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<26>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<25>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<24>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<23>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<22>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<21>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<20>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<19>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<18>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<17>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<16>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<15>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<14>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<13>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<12>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<11>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<10>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<9>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<8>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<7>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<6>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<5>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<4>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<3>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<2>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<1>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<0>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<47>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<46>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<45>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<44>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<43>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<42>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<41>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<40>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<39>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<38>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<37>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<36>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<35>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<34>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<33>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<32>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<31>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<30>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<29>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<28>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<27>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<26>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<25>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<24>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<23>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<22>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<21>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<20>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<19>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<18>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<17>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<16>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<15>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<14>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<13>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<12>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<11>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<10>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<9>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<8>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<7>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<6>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<5>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<4>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<3>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<2>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<1>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<0>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<17>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<16>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<15>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<14>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<13>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<12>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<11>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<10>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<9>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<8>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<7>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<6>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<5>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<4>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<3>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<2>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<1>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<0>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<47>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<46>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<45>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<44>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<43>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<42>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<41>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<40>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<39>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<38>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<37>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<36>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<35>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<34>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<33>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<32>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<31>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<30>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<29>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<28>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<27>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<26>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<25>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<24>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<23>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<22>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<21>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<20>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<19>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<18>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<17>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<16>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<15>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<14>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<13>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<12>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<11>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<10>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<9>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<8>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<7>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<6>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<5>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<4>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<3>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<2>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<1>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<0>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<35>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<34>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<33>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<32>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<31>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<30>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<29>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<28>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<27>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<26>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<25>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<24>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<23>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<22>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<21>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<20>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<19>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<18>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<17>_UNCONNECTED ;
  wire \NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<16>_UNCONNECTED ;
  wire [7 : 0] a_2;
  wire [7 : 0] b_3;
  wire [15 : 0] p_4;
  wire [0 : 0] \BU2/pcasc ;
  assign
    a_2[7] = a[7],
    a_2[6] = a[6],
    a_2[5] = a[5],
    a_2[4] = a[4],
    a_2[3] = a[3],
    a_2[2] = a[2],
    a_2[1] = a[1],
    a_2[0] = a[0],
    b_3[7] = b[7],
    b_3[6] = b[6],
    b_3[5] = b[5],
    b_3[4] = b[4],
    b_3[3] = b[3],
    b_3[2] = b[2],
    b_3[1] = b[1],
    b_3[0] = b[0],
    p[15] = p_4[15],
    p[14] = p_4[14],
    p[13] = p_4[13],
    p[12] = p_4[12],
    p[11] = p_4[11],
    p[10] = p_4[10],
    p[9] = p_4[9],
    p[8] = p_4[8],
    p[7] = p_4[7],
    p[6] = p_4[6],
    p[5] = p_4[5],
    p[4] = p_4[4],
    p[3] = p_4[3],
    p[2] = p_4[2],
    p[1] = p_4[1],
    p[0] = p_4[0];
  VCC   VCC_0 (
    .P(NLW_VCC_P_UNCONNECTED)
  );
  GND   GND_1 (
    .G(NLW_GND_G_UNCONNECTED)
  );
  DSP48A1 #(
    .CARRYINSEL ( "OPMODE5" ),
    .RSTTYPE ( "SYNC" ),
    .A0REG ( 0 ),
    .A1REG ( 0 ),
    .B1REG ( 0 ),
    .B0REG ( 0 ),
    .CREG ( 0 ),
    .MREG ( 1 ),
    .CARRYINREG ( 0 ),
    .OPMODEREG ( 0 ),
    .CARRYOUTREG ( 0 ),
    .PREG ( 0 ),
    .DREG ( 0 ))
  \BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171  (
    .CECARRYIN(\BU2/pcasc [0]),
    .RSTC(\BU2/pcasc [0]),
    .RSTCARRYIN(\BU2/pcasc [0]),
    .CED(\BU2/pcasc [0]),
    .RSTD(\BU2/pcasc [0]),
    .CEOPMODE(\BU2/pcasc [0]),
    .CEC(\BU2/pcasc [0]),
    .CARRYOUTF(\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_CARRYOUTF_UNCONNECTED ),
    .RSTOPMODE(\BU2/pcasc [0]),
    .RSTM(\BU2/pcasc [0]),
    .CLK(clk),
    .RSTB(\BU2/pcasc [0]),
    .CEM(\BU2/N1 ),
    .CEB(\BU2/pcasc [0]),
    .CARRYIN(\BU2/pcasc [0]),
    .CEP(\BU2/pcasc [0]),
    .CEA(\BU2/pcasc [0]),
    .CARRYOUT(\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_CARRYOUT_UNCONNECTED ),
    .RSTA(\BU2/pcasc [0]),
    .RSTP(\BU2/pcasc [0]),
    .B({\BU2/pcasc [0], \BU2/pcasc [0], b_3[7], b_3[7], b_3[7], b_3[7], b_3[7], b_3[7], b_3[7], b_3[7], b_3[7], b_3[6], b_3[5], b_3[4], b_3[3], b_3[2]
, b_3[1], b_3[0]}),
    .BCOUT({\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<17>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<16>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<15>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<14>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<13>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<12>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<11>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<10>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<9>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<8>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<7>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<6>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<5>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<4>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<3>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<2>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<1>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_BCOUT<0>_UNCONNECTED }),
    .PCIN({\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<47>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<46>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<45>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<44>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<43>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<42>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<41>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<40>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<39>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<38>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<37>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<36>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<35>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<34>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<33>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<32>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<31>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<30>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<29>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<28>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<27>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<26>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<25>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<24>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<23>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<22>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<21>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<20>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<19>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<18>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<17>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<16>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<15>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<14>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<13>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<12>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<11>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<10>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<9>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<8>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<7>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<6>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<5>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<4>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<3>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<2>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<1>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCIN<0>_UNCONNECTED }),
    .C({\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<47>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<46>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<45>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<44>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<43>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<42>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<41>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<40>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<39>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<38>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<37>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<36>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<35>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<34>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<33>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<32>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<31>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<30>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<29>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<28>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<27>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<26>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<25>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<24>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<23>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<22>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<21>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<20>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<19>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<18>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<17>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<16>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<15>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<14>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<13>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<12>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<11>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<10>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<9>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<8>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<7>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<6>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<5>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<4>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<3>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<2>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<1>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_C<0>_UNCONNECTED }),
    .P({\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<47>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<46>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<45>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<44>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<43>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<42>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<41>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<40>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<39>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<38>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<37>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<36>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<35>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<34>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<33>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<32>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<31>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<30>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<29>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<28>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<27>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<26>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<25>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<24>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<23>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<22>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<21>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<20>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<19>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<18>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<17>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<16>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<15>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<14>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<13>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<12>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<11>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<10>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<9>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<8>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<7>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<6>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<5>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<4>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<3>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<2>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<1>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_P<0>_UNCONNECTED }),
    .OPMODE({\BU2/pcasc [0], \BU2/pcasc [0], \BU2/pcasc [0], \BU2/pcasc [0], \BU2/pcasc [0], \BU2/pcasc [0], \BU2/pcasc [0], \BU2/N1 }),
    .D({\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<17>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<16>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<15>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<14>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<13>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<12>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<11>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<10>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<9>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<8>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<7>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<6>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<5>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<4>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<3>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<2>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<1>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_D<0>_UNCONNECTED }),
    .PCOUT({\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<47>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<46>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<45>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<44>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<43>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<42>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<41>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<40>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<39>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<38>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<37>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<36>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<35>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<34>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<33>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<32>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<31>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<30>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<29>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<28>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<27>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<26>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<25>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<24>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<23>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<22>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<21>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<20>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<19>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<18>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<17>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<16>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<15>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<14>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<13>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<12>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<11>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<10>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<9>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<8>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<7>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<6>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<5>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<4>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<3>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<2>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<1>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_PCOUT<0>_UNCONNECTED }),
    .A({\BU2/pcasc [0], \BU2/pcasc [0], a_2[7], a_2[7], a_2[7], a_2[7], a_2[7], a_2[7], a_2[7], a_2[7], a_2[7], a_2[6], a_2[5], a_2[4], a_2[3], a_2[2]
, a_2[1], a_2[0]}),
    .M({\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<35>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<34>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<33>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<32>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<31>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<30>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<29>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<28>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<27>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<26>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<25>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<24>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<23>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<22>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<21>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<20>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<19>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<18>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<17>_UNCONNECTED , 
\NLW_BU2/U0/gEMBEDDED_MULT.gEMB_MULTS_only.gDSP.iDSP/Mmult_n0171_M<16>_UNCONNECTED , p_4[15], p_4[14], p_4[13], p_4[12], p_4[11], p_4[10], p_4[9], 
p_4[8], p_4[7], p_4[6], p_4[5], p_4[4], p_4[3], p_4[2], p_4[1], p_4[0]})
  );
  VCC   \BU2/XST_VCC  (
    .P(\BU2/N1 )
  );
  GND   \BU2/XST_GND  (
    .G(\BU2/pcasc [0])
  );

// synthesis translate_on

endmodule

// synthesis translate_off

`ifndef GLBL
`define GLBL

`timescale  1 ps / 1 ps

module glbl ();

    parameter ROC_WIDTH = 100000;
    parameter TOC_WIDTH = 0;

    wire GSR;
    wire GTS;
    wire PRLD;

    reg GSR_int;
    reg GTS_int;
    reg PRLD_int;

//--------   JTAG Globals --------------
    wire JTAG_TDO_GLBL;
    wire JTAG_TCK_GLBL;
    wire JTAG_TDI_GLBL;
    wire JTAG_TMS_GLBL;
    wire JTAG_TRST_GLBL;

    reg JTAG_CAPTURE_GLBL;
    reg JTAG_RESET_GLBL;
    reg JTAG_SHIFT_GLBL;
    reg JTAG_UPDATE_GLBL;
    reg JTAG_RUNTEST_GLBL;

    reg JTAG_SEL1_GLBL = 0;
    reg JTAG_SEL2_GLBL = 0 ;
    reg JTAG_SEL3_GLBL = 0;
    reg JTAG_SEL4_GLBL = 0;

    reg JTAG_USER_TDO1_GLBL = 1'bz;
    reg JTAG_USER_TDO2_GLBL = 1'bz;
    reg JTAG_USER_TDO3_GLBL = 1'bz;
    reg JTAG_USER_TDO4_GLBL = 1'bz;

    assign (weak1, weak0) GSR = GSR_int;
    assign (weak1, weak0) GTS = GTS_int;
    assign (weak1, weak0) PRLD = PRLD_int;

    initial begin
	GSR_int = 1'b1;
	PRLD_int = 1'b1;
	#(ROC_WIDTH)
	GSR_int = 1'b0;
	PRLD_int = 1'b0;
    end

    initial begin
	GTS_int = 1'b1;
	#(TOC_WIDTH)
	GTS_int = 1'b0;
    end

endmodule

`endif

// synthesis translate_on
